name: timeout2

on:
  push

jobs:
  timeout2:
    runs-on: ubuntu-latest
    steps:
      - name: foot_print_start_datetime
        run: date
      - name: long_run_step
        timeout-minutes: 2
        continue-on-error: true
        run: sleep 125
      - name: foot_print_end_datetime
        run: date
